// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX65vRkTAK-voJmNlyzEztruD6wdnsCWc',
    appId: '1:804926382699:web:a6eb9fccb83759ec46072e',
    messagingSenderId: '804926382699',
    projectId: 'my-project-chatapp-aee45',
    authDomain: 'my-project-chatapp-aee45.firebaseapp.com',
    storageBucket: 'my-project-chatapp-aee45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuaf1cTfxOUsE03NFj_Fl1JOZu5dtmmSg',
    appId: '1:804926382699:android:6ab74a68a49acddb46072e',
    messagingSenderId: '804926382699',
    projectId: 'my-project-chatapp-aee45',
    storageBucket: 'my-project-chatapp-aee45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBioHJ-Szkmpjj1As8bXcXq7izjArrxfLo',
    appId: '1:804926382699:ios:ffadfc35693abce546072e',
    messagingSenderId: '804926382699',
    projectId: 'my-project-chatapp-aee45',
    storageBucket: 'my-project-chatapp-aee45.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX65vRkTAK-voJmNlyzEztruD6wdnsCWc',
    appId: '1:804926382699:web:5b278beef3eec0f846072e',
    messagingSenderId: '804926382699',
    projectId: 'my-project-chatapp-aee45',
    authDomain: 'my-project-chatapp-aee45.firebaseapp.com',
    storageBucket: 'my-project-chatapp-aee45.firebasestorage.app',
  );
}
